# File: .github/workflows/publish-dita.yml
name: Publish DITA to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install DITA-OT
        run: |
          wget https://github.com/dita-ot/dita-ot/releases/download/3.6.1/dita-ot-3.6.1.zip
          unzip dita-ot-3.6.1.zip
          chmod +x dita-ot-3.6.1/bin/dita

      - name: Verify DITA files
        run: |
          echo "Checking DITA map and topics:"
          ls -la dita-source/maps/ || echo "Maps directory not found"
          ls -la dita-source/topics/ || echo "Topics directory not found"
          echo "Content of DITA map:"
          cat dita-source/maps/simple-guide.ditamap || echo "DITA map not found"

      - name: Transform DITA to HTML
        continue-on-error: true
        run: |
          ./dita-ot-3.6.1/bin/dita -i dita-source/maps/simple-guide.ditamap -o docs -f html5 \
          --args.copycss=yes \
          --args.css=custom.css \
          --args.cssroot=dita-source/css \
          --args.xhtml.toc=toc \
          --nav-toc=full \
          --args.outext=.html

      - name: Verify output
        run: |
          echo "Checking output files:"
          ls -la docs/ || echo "Output directory empty or not found"
          find docs -type f | sort || echo "No files found in output"

      # Fallback: create simple HTML if DITA-OT fails
      - name: Create simple HTML (fallback)
        if: ${{ failure() }}
        run: |
          mkdir -p docs
          echo "<html><head><title>Simple DITA Publication</title></head><body>" > docs/index.html
          echo "<h1>Simple DITA Publication</h1>" >> docs/index.html
          echo "<p>This is a simple DITA publication.</p>" >> docs/index.html
          
          # List available topics from DITA map
          echo "<h2>Available Topics:</h2><ul>" >> docs/index.html
          grep -o 'href="[^"]*"' dita-source/maps/simple-guide.ditamap | sed 's/href="//g' | sed 's/"//g' | while read -r topic; do
            echo "<li>$topic</li>" >> docs/index.html
          done
          echo "</ul>" >> docs/index.html
          
          echo "</body></html>" >> docs/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true