# Create header and footer for consistent navigation
      - name: Create header and footer
        run: |
          # Get title from previous step
          DOCS_TITLE="${{ steps.extract_title.outputs.docs_title }}"

          # Create directory for header and footer files
          mkdir -p custom-templates

          # Create header with consistent navigation and title
          cat > custom-templates/header.html << 'EOF'
<div id="site-header">
  <div class="site-title">
    <a href="index.html">TITLE_PLACEHOLDER</a>
  </div>
  <nav class="main-nav">
    <ul>
      <li><a href="topics/welcome.html">Test welcome page</a></li>
      <li><a href="topics/second-topic.html">Second Section</a></li>
      <li><a href="topics/Top.html">Welcome to My Simple DITA Publication</a>
        <ul>
          <li><a href="topics/test_2171_manual.html">test 2171 manual</a></li>
        </ul>
      </li>
    </ul>
  </nav>
</div>
<hr>
EOF

          # Replace placeholder with actual title
          sed -i "s/TITLE_PLACEHOLDER/$DOCS_TITLE/g" custom-templates/header.html

          # Create footer with title
          cat > custom-templates/footer.html << 'EOF'
<hr>
<div id="site-footer">
  <p>© 2025 TITLE_PLACEHOLDER | <a href="index.html">Home</a> | Last updated: <span id="last-updated"></span></p>
</div>
<script>
  // Highlight current page in navigation
  document.addEventListener('DOMContentLoaded', function() {
    const currentPath = window.location.pathname;
    const links = document.querySelectorAll('.main-nav a');

    links.forEach(link => {
      if (currentPath.endsWith(link.getAttribute('href'))) {
        link.classList.add('active');
        link.parentElement.classList.add('current');
      }
    });

    // Add last updated date
    document.getElementById('last-updated').textContent = new Date().toLocaleDateString();
  });
</script>
EOF

          # Replace placeholder with actual title in footer
          sed -i "s/TITLE_PLACEHOLDER/$DOCS_TITLE/g" custom-templates/footer.html