name: DITA Publishing

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install DITA-OT
        run: |
          wget -q https://github.com/dita-ot/dita-ot/releases/download/3.6.1/dita-ot-3.6.1.zip
          unzip -q dita-ot-3.6.1.zip
          chmod +x dita-ot-3.6.1/bin/dita

      - name: Create output directory
        run: mkdir -p docs

      - name: Build single-page HTML from existing content
        run: |
          # Find a DITA map file
          DITA_MAP=$(find . -name "*.ditamap" | head -1)
          
          if [ -z "$DITA_MAP" ]; then
            echo "No DITA map found - creating simple HTML page"
            
            # Create a simple HTML page
            cat > docs/index.html << 'ENDHTML'
<!DOCTYPE html>
<html>
<head>
  <title>DITA Documentation</title>
  <style>
    body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #0066cc; }
  </style>
</head>
<body>
  <h1>DITA Documentation</h1>
  <p>No DITA content was found to process. Please add DITA content to your repository.</p>
</body>
</html>
ENDHTML
          
          else
            echo "Found DITA map: $DITA_MAP"
            
            # Run DITA-OT
            ./dita-ot-3.6.1/bin/dita \
            --input="$DITA_MAP" \
            --format=html5 \
            --output=docs \
            --verbose
            
            # If transformation failed, create a fallback page
            if [ $? -ne 0 ]; then
              echo "DITA-OT transformation failed - creating fallback page"
              
              cat > docs/index.html << 'ENDHTML'
<!DOCTYPE html>
<html>
<head>
  <title>DITA Documentation</title>
  <style>
    body { font-family: sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #0066cc; }
  </style>
</head>
<body>
  <h1>DITA Documentation</h1>
  <p>DITA transformation failed. Please check your DITA content for errors.</p>
</body>
</html>
ENDHTML
            fi
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true