# File: .github/workflows/publish-dita.yml
name: Publish DITA to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install DITA-OT
        run: |
          wget https://github.com/dita-ot/dita-ot/releases/download/3.7.4/dita-ot-3.7.4.zip
          unzip dita-ot-3.7.4.zip
          chmod +x dita-ot-3.7.4/bin/dita

      - name: Build DITA
        run: |
          ./dita-ot-3.7.4/bin/dita -i dita-source/maps/simple-guide.ditamap -o docs -f html5 \
          --args.copycss=yes \
          --args.css=custom.css \
          --args.cssroot=dita-source/css \
          --args.xhtml.toc=toc \
          --nav-toc=full \
          --args.breadcrumbs=yes \
          --args.outext=.html

      - name: List generated files
        run: |
          echo "Generated files in docs directory:"
          ls -la docs/
          echo "Content of docs directory and subdirectories:"
          find docs -type f | sort

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages